### ISSUE TITLE
can you provide a exmaple to publish mp4?

### ISSUE THREAD

**Issue by notedit** [minsikzzang/rtmp-wrapper#1]

**Comment by minsikzzang** [comment]
Hi,

With only rtmp-wrapper, we cannot publish mp4 video. You need to have FLV format video to publish it. You can encoder your mp4 video to FLV on iOS with IFVideoPicker, see the project IFVideoPicker here.

Thanks
Min

**Comment by notedit** [comment]
thanks  that helps me a lots

**Comment by Phunk87** [comment]
HI,
I've just tried to encoder camera capture to FLV with IFVideoPicker, and then publish it to my local rtmp server, which running crtmpserver, app crashed.

I don't know if it is just i'm using it in wrong way, or there's some bug stuff.

I replace the file write invoke with [self.rtmpWrapper write:flvWriter_.packet]. You can see it in the following screenshot. I replace in both - (void)captureHandleByCompletedMP4Frames:(NSArray *)frames buffer:(NSData *)buffer and - (void)mp4MetaHeaderHandler:(MP4Reader *)reader method.

If you have tried to push rtmp stream successfully, maybe you can figure out what's wrong with my code. Thanks.

![2014-11-15 2 02 05](https://cloud.githubusercontent.com/assets/907754/5050710/6f621b5a-6c6b-11e4-8910-77d44c43eb19.png)
